server {
    listen 80;

    # ─── 1. Servir les fichiers React ───────────────────────────────
    location / {
        root   /usr/share/nginx/html;
        index  index.html;

        # Indispensable pour React Router :
        # Si le fichier n'existe pas, renvoyer index.html
        # (sinon /dashboard donne une 404 au refresh)
        try_files $uri $uri/ /index.html;
    }

    # ─── 2. Fichiers uploadés (PDF examens, etc.) ───────────────────
    location /uploads/ {
        proxy_pass http://backend:5000;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # ─── 3. Proxy vers le backend ────────────────────────────────────
    location /api/ {
        # "backend" = le nom du service dans docker-compose.yml
        # Docker résout ce nom automatiquement en interne
        proxy_pass http://backend:5000;

        # Transmettre les vraies infos de la requête au backend
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}